sudo: required
dist: trusty

services:
  - docker

language: node_js
node_js:
  - "5.1"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  global:
  - CXX=g++-4.8
  - secure: "pjcuRvCWI9GomSc0wA/hAUJqEvX0vry892aPAC1crmItffcmL+W6t4/Wbc68zVyGKON/gIopWe+As4Q9F/nXqcQaErm3r8YmCOMXqRBQPnRVRLKE+G09dDsqDEahPh9IKyVeIk+X4+l0p6C89VY4vd5NaWoDS+Fz2kmfBdb7YR0Pf0M9xsG4+iJU54nQDWdbWbH+W7otuSmerRNc1/hFigTMjhUrPyCx/68wq/tZ16jtHVfahkpS2w3sI616gl6xon3d2tKmd14ylA7Y52zTVDrPRvd2PfNktKvGGy2W2kSlRnZSSyouK1FFqa+yKSoL1YLnMEnAM0sDXYPGZZ+8MaKo/4qvTXv02Ezf7sRySZHvntkVOyL8JXK91PGvnOyFs6kdl7O6TlT6sQieBKk1mPKdo1q/inCfX1ZHSfFZVUP58+IdWo+VKw0ceVrajJseqQLWT9ZLsAsrCy//LSoIyx9Gjjqc2Hio/7nexA4C0hKXg2OLR2kCcpkbbXwzlogSXVlRPFA/PLKc40vyOcolDwn1RDQFM/9Y8K5dLcadlqzKwZz6BS2aKlqMx2OZCxBz2O31O9X7GzQmWvtkApKArHe7IbBZejMgzcT0nuuJBw+Lr2f8UdeXQCB10GFf0dRgQ4OJOpm8/7zSPTy9iZyjzQm60GVLCR1Vi88FLM1nSWU="
  - secure: "V7qGCg0T1cgLpq8Kt2UHhDNgiDDt2s+Q0b2P5FY4qDZRQTqMxrlDViM/Lc7fAEKecPjirgVMCVSUhlDtRflg35YkdbBbCI+zgrE6H5B3nHEvltFsI9yNtUoGZ1PJpBlUu6hSbvcyMbxIBvOyKhKL5rlCFunwnz5GaFrAzpw5RounKMtUPTKMLicQk0NoaCpDHOxZQNkz3vtGEd6m31fq5NeBior3vsQN/+e7zQoywKKXuDwREaTeNGnFE1+QOROoYjkX3b9r0jx3Ea/AdGkA5OjBKQQohZNHWbJs9p8U8zQqfcmC6GfD3DMRqonI6vSamrE5GslXvcP8IuI9ivCYaX7PKDW589KC3LlIhF02d2XG+I99zLB2sEiGM1kZwwz5GX/2pWwO9Ql+HeNvsVN1FMSn3SsdkZ4ElPWlrvu2EKslazbvoSJrWqCKxmJAuqrOdy1qw/O5enJ4Ef/IvawT/j/zEkmK536wDa790mPI6QerlUhKj4jfqObVw6gJaGirnhroKCqZue4ba9livJIXmEuxNb2LFqPQwru+YShfr+PW2Y5BReB1MiScgTY0frOcNe+RIZSVCD9B7dZaQ4dTo+7AEw8QvulSPj6VRxTb69zj803G9/TNwtVGRaWEwhZG80k8LiNMVCxY0tnsl1Q6pAntjXVWS5isUM266n6oAEw="
  - secure: "Uf8M8pdfE+IkhJspXIbySjp/jm4ozdZEDPyoabh3MU07Yv6y0Tfyvr3ZYt//kQbPyurExccTMbtEjVUL26Gi/on3S7QyaXAuAswnQWQcdcR2lxtljn9uWTncKXl4XOMfZ1jY7Zv6LfRCy0w6mo9lrWlHA2PaCTPaeV3vYGlvhKGNE5DznZ8c+FdjiHxl1kOe7SNHdDuOyHmEUaky+iOjI3aZ+NOnH5h8zJPN9UTy8xzUUr0jyAvDtcps0Zx81qULOmQzo3sLE+TQgA0AySKASJCJOjxm5R8iGRz2SDpBrZ1zC/ldvuoShhU6le+CkBf/1e+L534/jL2SVKL8Dfv72Z0UdInIXXOZZ+3tbMzkMvKGGirD2AnA3T5VZZGrNlzMGYNW6JoKQzOY9i2thrmTPcmbK1p8T/WNOQXoix/iv299kRVUsFjFZOMFmUf1XTxvXWWRvdc29XHCydEBkGu4NwxXt0V/58dJvV1ovmX3neVWYudOKQ8dh0wcsHqMtYn1mCAzlnuwfSgKATW9PPAhrnFS6JTz6yyEYH1SXuTuJfyHK0dYsYaJYexzpcqdzSBRo801EIlQppSZSzKaATuLPOnL3DIQ5b/eRRGki7DPYJzKJ2Da4BbW6IklL5aSCgpLDPxDcBk/mqSrMwCjmgE1BWsLswrD2HtuLQVAW/M6cJg="

after_success:
  - docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - export REPO=rainbeam/dapple-minimal
  - export COMMIT=${TRAVIS_COMMIT::8}
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      export TAG="latest"
      else export TAG=$TRAVIS_BRANCH
    fi
  - docker build -f Dockerfile.minimal -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
